import 'disaster_detail/models/details_page_model.dart';
import 'landing_page/models/landing_page_model.dart';

final List<DisasterList> disaster = [
  DisasterList(
    city: "Chennai",
    country: "India",
    criticalityRating: 5,
    eventStartDate: "2022-03-26",
    id: "ABC123",
    imageUrl: "",
    severity: "High",
    state: "Tamil Nadu",
    title: "Tunami - chennai",
    type: "Flood",
    requires: ["food", 'transport'],
  ),
  DisasterList(
    city: "Delhi",
    country: "India",
    criticalityRating: 5,
    eventStartDate: "2022-03-26",
    id: "ABC123",
    imageUrl: "",
    severity: "Low",
    state: "Tamil Nadu",
    title: "Gas Tragedy - Delhi",
    type: "Tradedy",
    requires: [
      "food",
      'transport',
      'shelter',
      'Monetory',
      'transport',
      'shelter',
      'Monetory'
    ],
  ),
  DisasterList(
    city: "Chennai",
    country: "India",
    criticalityRating: 5,
    eventStartDate: "2022-03-26",
    id: "ABC123",
    imageUrl: "",
    severity: "High",
    state: "Tamil Nadu",
    title: "Tunami - chennai",
    type: "Flood",
    requires: ["food", 'transport'],
  ),
  DisasterList(
    city: "Chennai",
    country: "India",
    criticalityRating: 5,
    eventStartDate: "2022-03-26",
    id: "ABC123",
    imageUrl: "",
    severity: "High",
    state: "Tamil Nadu",
    title: "Tunami - chennai",
    type: "Flood",
    requires: ["food", 'transport'],
  ),
  DisasterList(
    city: "Chennai",
    country: "India",
    criticalityRating: 5,
    eventStartDate: "2022-03-26",
    id: "ABC123",
    imageUrl: "",
    severity: "High",
    state: "Tamil Nadu",
    title: "Tunami - chennai",
    type: "Flood",
    requires: ["food", 'transport'],
  ),
];

DetailsPageModel detailsPageModel = DetailsPageModel(
  accepts: [
    "Food",
    "lunch",
    "money",
    "Food",
    "lunch",
    "money",
  ],
  description:
      "Both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass.",
  eventStartDate: '2022-03-26',
  financialLoss: "3L+",
  id: "ABC123",
  imageurl: "",
  lattitude: '200.0',
  longitude: '200.0',
  location: "Chennai, TamilNadu",
  name: "Tunami - Chennai",
  organizationCount: 2,
  peopleImpacted: 4000,
  organizations: [
    Organization(
      id: "12334",
      about:
          "Nuhor lir gurenna. Skorī demalyti tymptir tymis, erinis ia morghulis. Valar morghulis. Sikudi nopazmi! Tubi daor. Tubi daor. Hen syndrorro, onos. Hen nuqir, perzys. Hen morghot, glaeson.",
      accepts: ['Food', 'Transport', "manpower"],
      areaServed: 'Marine Drive',
      contact: "913355255",
      founded: "1977",
      founder: "MR.Madan Mohan",
      name: "Khalsa aid",
      registrationNo: "Bpha56",
      type: "PANINDIA",
      verified: true,
      volunteerCount: 3000,
      website: "ABC.com",
    ),
    Organization(
      id: "12334",
      about:
          "Nuhor lir gurenna. Skorī demalyti tymptir tymis, erinis ia morghulis. Valar morghulis. Sikudi nopazmi! Tubi daor. Tubi daor. Hen syndrorro, onos. Hen nuqir, perzys. Hen morghot, glaeson.",
      accepts: ['Food', 'Transport', "manpower"],
      areaServed: 'Marine Drive',
      contact: "913355255",
      founded: "1977",
      founder: "MR.Madan Mohan",
      name: "Khalsa aid",
      registrationNo: "Bpha56",
      type: "PANINDIA",
      verified: true,
      volunteerCount: 3000,
      website: "ABC.com",
    ),
    Organization(
      id: "12334",
      about:
          "Nuhor lir gurenna. Skorī demalyti tymptir tymis, erinis ia morghulis. Valar morghulis. Sikudi nopazmi! Tubi daor. Tubi daor. Hen syndrorro, onos. Hen nuqir, perzys. Hen morghot, glaeson.",
      accepts: ['Food', 'Transport', "manpower"],
      areaServed: 'Marine Drive',
      contact: "913355255",
      founded: "1977",
      founder: "MR.Madan Mohan",
      name: "Khalsa aid",
      registrationNo: "Bpha56",
      type: "PANINDIA",
      verified: true,
      volunteerCount: 3000,
      website: "ABC.com",
    ),
  ],
);
